import merge from 'deepmerge';
import type { Metadata } from 'next';

type MetadataGenerator = Omit<Metadata, 'description' | 'title'> & {
  title: string;
  description: string;
};

const name = 'Generated by create next app';

export const createMetadata = ({
  title,
  description,
  ...properties
}: MetadataGenerator): Metadata => {
  const parsed = `${title} | ${name}`;

  const base: Metadata = {
    title: {
      template: `%s | ${name}`,
      default: parsed,
    },
    description,
  };

  const metadata: Metadata = merge(base, properties);

  return metadata;
};
