import merge from 'deepmerge';
import type { Metadata } from 'next';

type MetadataGenerator = Omit<Metadata, 'description' | 'title'> & {
  title: string;
  description: string;
};

const name = 'Generated by create next app';

export const createMetadata = ({
  title,
  description,
  ...properties
}: MetadataGenerator): Metadata => {
  const parsed = `${title} | ${name}`;

  const defaultMetadata: Metadata = {
    title: parsed,
    description,
  };

  const metadata: Metadata = merge(defaultMetadata, properties);

  return metadata;
};
