import '@/styles/globals.css';

import type { Metadata, Viewport } from 'next';

import { Wrapper } from '@/components/wrapper';
import { fonts } from '@/lib/fonts';
import { cn } from '@/lib/utils';

const title = 'Create Next App';
const description = 'Generated by create next app';

export const metadata: Metadata = {
  title,
  description,
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

type RootLayoutProps = {
  readonly children: React.ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => (
  <html lang="en" suppressHydrationWarning={true}>
    <body className={cn('bg-background text-foreground', fonts)}>
      <Wrapper>
        <div className="px-4">
          <main className="container mx-auto mt-4 max-w-3xl!">{children}</main>
        </div>
      </Wrapper>
    </body>
  </html>
);

export default RootLayout;
