import '@/styles/globals.css';

import type { Metadata } from 'next';

import { Wrapper } from '@/components/wrapper';
import { fonts } from '@/lib/fonts';
import { createMetadata } from '@/lib/metadata';
import { cn } from '@/lib/utils';

export const metadata: Metadata = createMetadata({
  title: 'Create Next App',
  description: 'Generated by create next app',
});

type Props = {
  readonly children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn('', fonts)}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
