import type { Metadata } from 'next';

import { createMetadata } from '@/lib/metadata';

const title = 'Create Next App';
const description = 'Generated by create next app';

export const metadata: Metadata = createMetadata({ title, description });

const Home = () => {
  return (
    <main className="p-4">
      <h1>{title}</h1>
      <p>{description}</p>
    </main>
  );
};

export default Home;
